/* Rota Snow Finder — data.
   Every ski and snowboard resort in Spain worth the drive from NAVSTA Rota,
   with the numbers a first-timer actually needs: how far, how much, how
   friendly to a beginner, and where to park. Coordinates were geocoded and
   checked against a terrain model; drive times are hand-set from the naval
   station gate (36.6290, -6.3400) with no stops.

   Prices are the last published season's adult rates and move every year —
   the page says so, and the Live check asks the web for today's number. */
window.__SNOW_ORIGIN__ = { lat: 36.6290, lon: -6.3400, label: "NAVSTA Rota" };

/* Season dates are the resort's usual pattern, month-day. Actual dates are
   announced each autumn and depend on snow; the Live check confirms. */
window.__SNOW_RESORTS__ = [
  {
    id: "sierra-nevada", name: "Sierra Nevada", area: "Pradollano · Granada", region: "Andalucía",
    lat: 37.0943, lon: -3.3991, elev: 2100, top: { lat: 37.0560, lon: -3.3650, elev: 3300 },
    km: 110, lifts: 21, learn: 5, driveMin: 255, distKm: 380,
    season: { open: "11-28", close: "05-03" },
    price: { low: 55, high: 63, rentSki: 30, rentBoard: 32, lessonGroup: 55, lessonPrivate: 70, parking: 25 },
    official: "https://sierranevada.es",
    park: { lat: 37.0982, lon: -3.3930, text: "Multi-storey pay car parks at the top of Pradollano (Los Peñones is the big one). About €20–30 a day in high season and full by 09:30 on a Saturday — arrive before nine, or park lower down and ride the free shuttle." },
    route: "A-4 to Sevilla, A-92 across to Granada, Ronda Sur (A-44) to the A-395, then 30 km of hairpins up to Pradollano. No tolls.",
    chains: "The A-395 above 1,500 m can be chains-only after a storm and the Guardia Civil turns back cars without them. Keep a set in the boot from December on and practise fitting them once at home.",
    why: "The only resort in Andalucía, the highest in Spain, and the closest to Rota by five hours. The beginner zone at Borreguiles (2,650 m) is huge, flat, sunny and served by magic carpets — the best first day in the country.",
    learnNote: "Take the gondola from Pradollano straight to Borreguiles: everything for a first-timer is up there. The ski school has English-speaking instructors; the British Ski Center runs lessons in English only. Book the day before — weekend classes sell out.",
    bus: "ALSA runs three buses a day from Granada bus station to Pradollano (about €5–9 each way, 45 min). Park in Granada and you skip chains and the car park.",
    stay: "Pradollano itself (walk to the gondola, €90–160), Monachil or Güéjar Sierra (villages 30 min down, €50–90), or Granada city (45 min, cheapest, and the Alhambra at night).",
    warn: "It is 3,000 m and Andalusian sun — SPF 50 on day one or you burn under the goggles. Wind closes the top lifts often; Borreguiles usually stays open.",
    tags: ["closest", "beginner", "big"],
  },
  {
    id: "la-covatilla", name: "Sierra de Béjar – La Covatilla", area: "Béjar · Salamanca", region: "Castilla y León",
    lat: 40.3485, lon: -5.6872, elev: 1980, top: { lat: 40.3520, lon: -5.6960, elev: 2369 },
    km: 24, lifts: 5, learn: 3, driveMin: 330, distKm: 500,
    season: { open: "12-12", close: "03-28" },
    price: { low: 35, high: 40, rentSki: 22, rentBoard: 25, lessonGroup: 40, lessonPrivate: 55, parking: 0 },
    official: "https://www.sierradebejar-lacovatilla.com",
    park: { lat: 40.3485, lon: -5.6872, text: "Free car park at the base building; the last 12 km from Béjar are a narrow mountain road." },
    route: "A-4 to Sevilla, A-66 (Ruta de la Plata) north past Mérida and Cáceres to Béjar, then the SA-CV-62 up. No tolls.",
    chains: "The access road is often chains-only and closes in strong wind. Check the resort's web before leaving Béjar.",
    why: "The second-closest lift to Rota, and cheap. A small, windy, unreliable resort — a decent second trip, not a first.",
    learnNote: "One small beginner area by the base. Fine for a cheap second weekend once you can stop; not the place for day one.",
    warn: "Wind shuts the lifts more days than snow does. A €35 pass is no bargain if the mountain is closed — check the Live line before you drive five hours.",
    tags: ["cheap", "small"],
  },
  {
    id: "valdesqui", name: "Valdesquí", area: "Rascafría · Madrid", region: "Madrid",
    lat: 40.8048, lon: -3.9698, elev: 1860, top: { lat: 40.8140, lon: -3.9600, elev: 2280 },
    km: 22, lifts: 14, learn: 3, driveMin: 420, distKm: 690,
    season: { open: "12-05", close: "03-31" },
    price: { low: 42, high: 48, rentSki: 25, rentBoard: 28, lessonGroup: 45, lessonPrivate: 60, parking: 0 },
    official: "https://www.valdesqui.es",
    park: { lat: 40.8048, lon: -3.9698, text: "Free car park at the base; on a snowy weekend it fills by 08:30 and the M-604 closes to more cars. Weekday or very early." },
    route: "A-4 to Madrid, then M-607 / M-604 over the Puerto de Cotos. About seven hours.",
    chains: "The M-604 over Cotos is regularly chains-only. Madrid police check.",
    why: "Madrid's ski hill. Close to the capital, so it is busy, small and priced like a city — but it has a proper beginner zone and everything is rentable on site.",
    learnNote: "A dedicated beginner area with carpets. Weekend queues are long; a weekday in January is a different place.",
    warn: "Sells out: passes are sold online with a cap and the car park has a hard limit. Book the pass before leaving Rota.",
    tags: ["small", "busy"],
  },
  {
    id: "navacerrada", name: "Puerto de Navacerrada", area: "Cercedilla · Madrid", region: "Madrid",
    lat: 40.7844, lon: -4.0047, elev: 1860, top: { lat: 40.7800, lon: -4.0100, elev: 2200 },
    km: 6, lifts: 5, learn: 2, driveMin: 400, distKm: 660,
    season: { open: "12-20", close: "03-15" },
    price: { low: 30, high: 35, rentSki: 22, rentBoard: 25, lessonGroup: 40, lessonPrivate: 55, parking: 0 },
    official: "https://www.puertonavacerrada.com",
    park: { lat: 40.7844, lon: -4.0047, text: "Roadside and a small lot at the pass; fills fast. Train from Cercedilla is the smart way in." },
    route: "A-4 to Madrid, A-6 / M-601 up to the pass.",
    chains: "M-601 is chains-only after snow.",
    why: "Historic, tiny, half of it closed by the national park. Only worth it if you are already in Madrid.",
    learnNote: "A couple of gentle runs by the pass. Not worth the drive from Rota just to learn.",
    warn: "Uncertain future — several of its lifts were ordered closed. Check it is running at all.",
    tags: ["small"],
  },
  {
    id: "la-pinilla", name: "La Pinilla", area: "Cerezo de Arriba · Segovia", region: "Castilla y León",
    lat: 41.1973, lon: -3.4750, elev: 1500, top: { lat: 41.1900, lon: -3.4900, elev: 2273 },
    km: 22, lifts: 11, learn: 3, driveMin: 445, distKm: 740,
    season: { open: "12-05", close: "03-28" },
    price: { low: 38, high: 44, rentSki: 24, rentBoard: 27, lessonGroup: 45, lessonPrivate: 60, parking: 0 },
    official: "https://www.lapinilla.es",
    park: { lat: 41.1973, lon: -3.4750, text: "Free car parks at the base station." },
    route: "A-4 to Madrid, A-1 north to Cerezo de Arriba, then 8 km up.",
    chains: "Access road is short and usually cleared; chains rarely required.",
    why: "Quieter than Valdesquí, a proper beginner zone, and snowmaking that keeps it open when Madrid's hills are bare. In summer it is a bike park.",
    learnNote: "Beginner area with carpets at the base; ski school on site.",
    warn: "Low base at 1,500 m — warm weeks strip the lower runs.",
    tags: ["beginner"],
  },
  {
    id: "javalambre", name: "Javalambre", area: "Camarena de la Sierra · Teruel", region: "Aragón",
    lat: 40.1152, lon: -1.0178, elev: 1650, top: { lat: 40.1050, lon: -1.0100, elev: 2000 },
    km: 14, lifts: 8, learn: 4, driveMin: 480, distKm: 800,
    season: { open: "12-05", close: "03-28" },
    price: { low: 35, high: 40, rentSki: 22, rentBoard: 25, lessonGroup: 40, lessonPrivate: 55, parking: 0 },
    official: "https://www.aramon.com/estaciones/javalambre",
    park: { lat: 40.1152, lon: -1.0178, text: "Free car park at the base." },
    route: "A-4 to Córdoba, A-4 / A-31 towards Albacete, then the A-23 north to Teruel and the mountain road up. Long.",
    chains: "Short access road, usually cleared.",
    why: "Small, cheap, gentle, empty on weekdays. Built for families and first-timers. Same Aramón pass as Valdelinares next door.",
    learnNote: "Almost the whole hill is green and blue. A very forgiving place to learn — if you were already in Valencia.",
    warn: "Too far from Rota for a weekend unless you are flying to Valencia and renting a car (1 h 45 from the airport).",
    tags: ["cheap", "beginner", "small"],
  },
  {
    id: "valdelinares", name: "Valdelinares", area: "Gúdar-Javalambre · Teruel", region: "Aragón",
    lat: 40.3823, lon: -0.6312, elev: 1700, top: { lat: 40.3900, lon: -0.6400, elev: 2024 },
    km: 15, lifts: 8, learn: 4, driveMin: 500, distKm: 830,
    season: { open: "12-05", close: "03-28" },
    price: { low: 35, high: 40, rentSki: 22, rentBoard: 25, lessonGroup: 40, lessonPrivate: 55, parking: 0 },
    official: "https://www.aramon.com/estaciones/valdelinares",
    park: { lat: 40.3823, lon: -0.6312, text: "Free car park at the base." },
    route: "Via Valencia and the A-23 to Teruel, then mountain roads.",
    chains: "Access road climbs to 1,700 m; chains after snow.",
    why: "Javalambre's twin: small, cheap, gentle. Highest village in Spain next door.",
    learnNote: "Beginner-friendly layout; good ski school.",
    warn: "Same distance problem as Javalambre.",
    tags: ["cheap", "beginner", "small"],
  },
  {
    id: "manzaneda", name: "Manzaneda", area: "Trives · Ourense", region: "Galicia",
    lat: 42.2571, lon: -7.2979, elev: 1500, top: { lat: 42.2500, lon: -7.3000, elev: 1780 },
    km: 17, lifts: 6, learn: 3, driveMin: 525, distKm: 850,
    season: { open: "12-20", close: "03-15" },
    price: { low: 30, high: 35, rentSki: 20, rentBoard: 22, lessonGroup: 35, lessonPrivate: 50, parking: 0 },
    official: "https://www.manzaneda.com",
    park: { lat: 42.2571, lon: -7.2979, text: "Free car park at the station." },
    route: "A-66 north through Extremadura, A-52 into Galicia.",
    chains: "Access road often needs chains; the station sometimes runs without snow at all.",
    why: "Galicia's only resort. Low, wet, unreliable — but a whole mountain resort with lodging and a wind-free feel.",
    learnNote: "Gentle terrain when it has snow. Rarely worth planning around from Rota.",
    warn: "Some winters it barely opens.",
    tags: ["small", "cheap"],
  },
  {
    id: "san-isidro", name: "San Isidro", area: "Puebla de Lillo · León", region: "Castilla y León",
    lat: 43.0654, lon: -5.3862, elev: 1500, top: { lat: 43.0500, lon: -5.4000, elev: 2100 },
    km: 27, lifts: 15, learn: 3, driveMin: 540, distKm: 880,
    season: { open: "12-05", close: "04-06" },
    price: { low: 33, high: 38, rentSki: 22, rentBoard: 25, lessonGroup: 40, lessonPrivate: 55, parking: 0 },
    official: "https://www.san-isidro.net",
    park: { lat: 43.0654, lon: -5.3862, text: "Three sectors, each with free parking (Cebolledo, Salencias, Requejines)." },
    route: "A-66 north to León, then N-625 / LE-331 into the Cantabrian mountains.",
    chains: "Mountain road; chains common in January.",
    why: "The biggest resort in the Cantabrian range, run by the province, cheap and honest.",
    learnNote: "Cebolledo sector has the beginner runs and the school.",
    warn: "Fog and wind off the Atlantic close it more than the Pyrenees.",
    tags: ["cheap"],
  },
  {
    id: "pajares", name: "Valgrande-Pajares", area: "Lena · Asturias", region: "Asturias",
    lat: 42.9744, lon: -5.7776, elev: 1350, top: { lat: 42.9700, lon: -5.7900, elev: 1870 },
    km: 24, lifts: 9, learn: 3, driveMin: 540, distKm: 880,
    season: { open: "12-12", close: "03-31" },
    price: { low: 28, high: 32, rentSki: 20, rentBoard: 22, lessonGroup: 35, lessonPrivate: 50, parking: 0 },
    official: "https://www.valgrande-pajares.com",
    park: { lat: 42.9744, lon: -5.7776, text: "Free car park at the Brañillín base." },
    route: "A-66 north to León and over the Puerto de Pajares.",
    chains: "The old N-630 pass road is chains-only in storms; the AP-66 tunnel is the reliable way.",
    why: "Old-school Asturian resort, one of the cheapest passes in Spain.",
    learnNote: "Small beginner zone at the base with a carpet.",
    warn: "Low and Atlantic: rain at the base is common.",
    tags: ["cheap", "small"],
  },
  {
    id: "fuentes-de-invierno", name: "Fuentes de Invierno", area: "Aller · Asturias", region: "Asturias",
    lat: 43.0635, lon: -5.3939, elev: 1500, top: { lat: 43.0550, lon: -5.4050, elev: 1900 },
    km: 9, lifts: 5, learn: 3, driveMin: 555, distKm: 900,
    season: { open: "12-12", close: "03-31" },
    price: { low: 28, high: 32, rentSki: 20, rentBoard: 22, lessonGroup: 35, lessonPrivate: 50, parking: 0 },
    official: "https://www.fuentesdeinvierno.com",
    park: { lat: 43.0635, lon: -5.3939, text: "Free car park at the base." },
    route: "A-66 to León, then over the Puerto de San Isidro from the Asturian side.",
    chains: "Chains often required on the pass.",
    why: "Tiny sister of San Isidro across the pass. Cheap, quiet, modern lifts.",
    learnNote: "One gentle sector with a carpet.",
    warn: "Nine kilometres of piste: you will run out of runs by lunch once you can turn.",
    tags: ["cheap", "small"],
  },
  {
    id: "leitariegos", name: "Leitariegos", area: "Villablino · León", region: "Castilla y León",
    lat: 42.9893, lon: -6.4174, elev: 1500, top: { lat: 42.9850, lon: -6.4300, elev: 1900 },
    km: 7, lifts: 5, learn: 4, driveMin: 570, distKm: 920,
    season: { open: "12-20", close: "03-15" },
    price: { low: 22, high: 26, rentSki: 18, rentBoard: 20, lessonGroup: 30, lessonPrivate: 45, parking: 0 },
    official: "https://www.leitariegos.net",
    park: { lat: 42.9893, lon: -6.4174, text: "Free parking at the pass." },
    route: "A-66 north to Benavente, then A-52 and CL-626 into Laciana.",
    chains: "Mountain pass; chains after snow.",
    why: "The cheapest pass in Spain, and the whole hill is beginner-grade. A family hill.",
    learnNote: "Everything here is gentle. Perfect terrain, wrong distance.",
    warn: "Far, small, and snow-dependent.",
    tags: ["cheap", "beginner", "small"],
  },
  {
    id: "alto-campoo", name: "Alto Campoo", area: "Reinosa · Cantabria", region: "Cantabria",
    lat: 43.0369, lon: -4.3869, elev: 1650, top: { lat: 43.0250, lon: -4.3950, elev: 2125 },
    km: 28, lifts: 13, learn: 3, driveMin: 570, distKm: 950,
    season: { open: "12-05", close: "04-06" },
    price: { low: 38, high: 42, rentSki: 22, rentBoard: 25, lessonGroup: 40, lessonPrivate: 55, parking: 0 },
    official: "https://altocampoo.com",
    park: { lat: 43.0369, lon: -4.3869, text: "Free car parks at the base; a big one fills on Cantabrian holidays." },
    route: "A-66 to Benavente, A-231 to Burgos, A-67 up to Reinosa, then 25 km to the station.",
    chains: "Access road often chains-only after snowfall.",
    why: "Cantabria's resort, wide open bowls above the tree line, reasonable price.",
    learnNote: "Good beginner sector by the base building.",
    warn: "Exposed: wind closes it, and Atlantic fog can erase the whole mountain.",
    tags: ["cheap"],
  },
  {
    id: "lunada", name: "Lunada", area: "Espinosa de los Monteros · Burgos", region: "Castilla y León",
    lat: 43.1658, lon: -3.6547, elev: 1300, top: { lat: 43.1700, lon: -3.6600, elev: 1600 },
    km: 4, lifts: 3, learn: 3, driveMin: 600, distKm: 1000,
    season: { open: "12-20", close: "03-01" },
    price: { low: 22, high: 26, rentSki: 18, rentBoard: 20, lessonGroup: 30, lessonPrivate: 45, parking: 0 },
    official: "https://www.estaciondeesquilunada.com",
    park: { lat: 43.1658, lon: -3.6547, text: "Roadside parking at the pass." },
    route: "A-66 and A-231 to Burgos, then north.",
    chains: "Pass road; chains after snow.",
    why: "Four kilometres of piste on a foggy pass. Listed so you know it exists, not so you drive there.",
    learnNote: "Gentle, but rarely open.",
    warn: "Opens only in good snow years.",
    tags: ["small", "cheap"],
  },
  {
    id: "candanchu", name: "Candanchú", area: "Aísa · Huesca", region: "Aragón",
    lat: 42.7854, lon: -0.5267, elev: 1530, top: { lat: 42.7750, lon: -0.5400, elev: 2400 },
    km: 50, lifts: 24, learn: 3, driveMin: 600, distKm: 1010,
    season: { open: "12-05", close: "04-06" },
    price: { low: 47, high: 52, rentSki: 25, rentBoard: 28, lessonGroup: 45, lessonPrivate: 60, parking: 0 },
    official: "https://candanchu.com",
    park: { lat: 42.7854, lon: -0.5267, text: "Free car parks along the N-330 at the base." },
    route: "Via Madrid and Zaragoza, A-23 north to Jaca, N-330 up towards the French border.",
    chains: "N-330 to the Somport; chains after storms.",
    why: "Spain's oldest resort, steep and old-fashioned, cheaper than its neighbours. Shares a pass with Astún next door.",
    learnNote: "Beginner zone at the base (Pista Grande). The rest is for later.",
    warn: "Famous for steep runs — do not wander off the beginner zone.",
    tags: ["pyrenees"],
  },
  {
    id: "astun", name: "Astún", area: "Jaca · Huesca", region: "Aragón",
    lat: 42.8110, lon: -0.5100, elev: 1700, top: { lat: 42.8200, lon: -0.5000, elev: 2300 },
    km: 50, lifts: 14, learn: 4, driveMin: 605, distKm: 1015,
    season: { open: "12-05", close: "04-06" },
    price: { low: 50, high: 54, rentSki: 25, rentBoard: 28, lessonGroup: 45, lessonPrivate: 60, parking: 0 },
    official: "https://www.astun.com",
    park: { lat: 42.8110, lon: -0.5100, text: "Free car park right at the base — one of the closest to the lifts in the Pyrenees." },
    route: "Via Zaragoza and Jaca, N-330 then the Astún road.",
    chains: "Chains after storms on the last kilometres.",
    why: "A compact bowl with everything visible from the base, a big beginner area and a joint pass with Candanchú.",
    learnNote: "Wide beginner slope right by the car park, magic carpets, ski school at the base.",
    warn: "Eleven hours in the car. Fly to Zaragoza and rent instead.",
    tags: ["pyrenees", "beginner"],
  },
  {
    id: "formigal", name: "Formigal-Panticosa", area: "Sallent de Gállego · Huesca", region: "Aragón",
    lat: 42.7741, lon: -0.3609, elev: 1500, top: { lat: 42.7900, lon: -0.3400, elev: 2250 },
    km: 176, lifts: 37, learn: 4, driveMin: 615, distKm: 1040,
    season: { open: "11-28", close: "04-12" },
    price: { low: 58, high: 66, rentSki: 30, rentBoard: 33, lessonGroup: 55, lessonPrivate: 70, parking: 0 },
    official: "https://www.formigal-panticosa.com",
    park: { lat: 42.7741, lon: -0.3609, text: "Four valleys, each with a free car park (Sextas is the main one and fills first). Free ski bus between them." },
    route: "Via Zaragoza, A-23 north to Sabiñánigo, A-136 up the Tena valley.",
    chains: "A-136 to Formigal; chains after snowfall.",
    why: "The biggest ski area in Spain with Panticosa attached. Aramón's flagship — modern lifts, big beginner zones, prices to match.",
    learnNote: "Beginner areas at Sextas and Anayet with carpets; large English-speaking ski school. Panticosa side is quieter for learning.",
    warn: "Dynamic pricing: the day pass costs more the later you buy it. Buy online a week ahead.",
    tags: ["pyrenees", "big", "beginner"],
  },
  {
    id: "cerler", name: "Cerler", area: "Benasque · Huesca", region: "Aragón",
    lat: 42.5927, lon: 0.5384, elev: 1500, top: { lat: 42.5500, lon: 0.5300, elev: 2630 },
    km: 80, lifts: 19, learn: 3, driveMin: 645, distKm: 1080,
    season: { open: "12-05", close: "04-12" },
    price: { low: 55, high: 62, rentSki: 28, rentBoard: 30, lessonGroup: 50, lessonPrivate: 65, parking: 0 },
    official: "https://www.cerler.com",
    park: { lat: 42.5927, lon: 0.5384, text: "Free car parks at Cerler village and Ampriu." },
    route: "Via Zaragoza and Barbastro, N-260 up the Ésera valley to Benasque.",
    chains: "Long valley road; chains after storms.",
    why: "Highest peak in the Aragonese Pyrenees, long descents, a real mountain village at the bottom.",
    learnNote: "Beginner zone at Ampriu; steeper overall than Formigal.",
    warn: "Far from anywhere; the valley road is slow.",
    tags: ["pyrenees"],
  },
  {
    id: "boi-taull", name: "Boí Taüll", area: "Vall de Boí · Lleida", region: "Catalunya",
    lat: 42.4730, lon: 0.8744, elev: 2020, top: { lat: 42.4600, lon: 0.8600, elev: 2751 },
    km: 45, lifts: 12, learn: 4, driveMin: 660, distKm: 1100,
    season: { open: "12-05", close: "04-06" },
    price: { low: 48, high: 55, rentSki: 27, rentBoard: 30, lessonGroup: 50, lessonPrivate: 65, parking: 0 },
    official: "https://www.boitaullresort.com",
    park: { lat: 42.4730, lon: 0.8744, text: "Free car park at the base at 2,020 m." },
    route: "Via Lleida, N-230 up to Pont de Suert, then the Boí valley.",
    chains: "The last 12 km climb to 2,000 m; chains after snow.",
    why: "Highest base in the Pyrenees — reliable snow, no crowds, quiet valley of Romanesque churches.",
    learnNote: "Beginner zone at the base with carpets; wide, quiet blues above.",
    warn: "Cold and high: a beginner's first day here is colder than Sierra Nevada's.",
    tags: ["pyrenees", "beginner"],
  },
  {
    id: "port-aine", name: "Port Ainé", area: "Rialp · Lleida", region: "Catalunya",
    lat: 42.4234, lon: 1.2151, elev: 1650, top: { lat: 42.4100, lon: 1.2200, elev: 2440 },
    km: 27, lifts: 8, learn: 4, driveMin: 660, distKm: 1090,
    season: { open: "12-05", close: "04-06" },
    price: { low: 42, high: 48, rentSki: 25, rentBoard: 28, lessonGroup: 45, lessonPrivate: 60, parking: 0 },
    official: "https://portaine.cat",
    park: { lat: 42.4234, lon: 1.2151, text: "Free car park at the hotel and lifts." },
    route: "Via Lleida and the C-13 up the Noguera Pallaresa.",
    chains: "Long access road; chains after snow.",
    why: "Family resort with a hotel at the lifts; gentle and cheap for the Pyrenees.",
    learnNote: "Big gentle sector at the top of the first lift; good for learning.",
    warn: "Small once you are past the basics.",
    tags: ["pyrenees", "beginner", "cheap"],
  },
  {
    id: "espot", name: "Espot Esquí", area: "Espot · Lleida", region: "Catalunya",
    lat: 42.5509, lon: 1.0802, elev: 1500, top: { lat: 42.5400, lon: 1.0700, elev: 2500 },
    km: 25, lifts: 6, learn: 3, driveMin: 675, distKm: 1110,
    season: { open: "12-05", close: "04-06" },
    price: { low: 42, high: 45, rentSki: 25, rentBoard: 28, lessonGroup: 45, lessonPrivate: 60, parking: 0 },
    official: "https://espotesqui.cat",
    park: { lat: 42.5509, lon: 1.0802, text: "Free car park at the base." },
    route: "Via Lleida and Sort.",
    chains: "Chains after snow.",
    why: "Gateway to Aigüestortes national park; quiet, tree-lined.",
    learnNote: "Beginner zone by the base.",
    warn: "Small and far.",
    tags: ["pyrenees", "small"],
  },
  {
    id: "baqueira", name: "Baqueira Beret", area: "Val d'Aran · Lleida", region: "Catalunya",
    lat: 42.6993, lon: 0.9316, elev: 1500, top: { lat: 42.6880, lon: 0.9560, elev: 2610 },
    km: 167, lifts: 36, learn: 4, driveMin: 690, distKm: 1170,
    season: { open: "11-28", close: "04-19" },
    price: { low: 62, high: 72, rentSki: 35, rentBoard: 38, lessonGroup: 60, lessonPrivate: 80, parking: 0 },
    official: "https://www.baqueira.es",
    park: { lat: 42.6993, lon: 0.9316, text: "Free car parks at Baqueira 1500, Beret and Bonaigua; the 1500 one fills by 09:30." },
    route: "Via Lleida, N-230 through the Vielha tunnel into the Val d'Aran.",
    chains: "The Bonaigua pass is chains-only in storms; the Vielha tunnel side is reliable.",
    why: "The best resort in Spain by a distance: the most piste, the best lifts, the royal family's choice, and priced like it.",
    learnNote: "Beret sector is flat, wide and made for beginners; the ski school is huge and English is normal.",
    warn: "The most expensive weekend in Spanish skiing. Save it for when you can already turn.",
    tags: ["pyrenees", "big", "beginner"],
  },
  {
    id: "la-molina", name: "La Molina", area: "Alp · Girona", region: "Catalunya",
    lat: 42.3360, lon: 1.9490, elev: 1700, top: { lat: 42.3180, lon: 1.9010, elev: 2537 },
    km: 71, lifts: 16, learn: 5, driveMin: 690, distKm: 1190,
    season: { open: "11-28", close: "04-12" },
    price: { low: 52, high: 58, rentSki: 28, rentBoard: 30, lessonGroup: 50, lessonPrivate: 65, parking: 0 },
    official: "https://www.lamolina.cat",
    park: { lat: 42.3360, lon: 1.9490, text: "Free car parks at the base and at Alp 2500. Or arrive by train: the R3 from Barcelona stops at La Molina station and a bus climbs to the lifts." },
    route: "Via Barcelona and the C-16 Cadí tunnel, or the train from Barcelona Sants.",
    chains: "Tunnel route rarely needs chains; the Collada de Toses pass does.",
    why: "Spain's first ski resort and still its beginner capital: a whole sector of gentle runs, and the only one you can reach by train with no car at all. Joined to Masella as Alp 2500.",
    learnNote: "The beginner sector at the base (Pista Llarga) is the classic first-day slope of Catalonia. Ski school runs English classes; carpets and a slow chair.",
    warn: "Busy with school groups on weekdays in January and February.",
    tags: ["pyrenees", "beginner", "big", "train"],
  },
  {
    id: "masella", name: "Masella", area: "Alp · Girona", region: "Catalunya",
    lat: 42.3511, lon: 1.9012, elev: 1600, top: { lat: 42.3180, lon: 1.9010, elev: 2537 },
    km: 74, lifts: 18, learn: 4, driveMin: 690, distKm: 1190,
    season: { open: "11-28", close: "04-12" },
    price: { low: 52, high: 58, rentSki: 28, rentBoard: 30, lessonGroup: 50, lessonPrivate: 65, parking: 0 },
    official: "https://www.masella.com",
    park: { lat: 42.3511, lon: 1.9012, text: "Free car park at the base at Pla de Masella." },
    route: "Via Barcelona and the C-16.",
    chains: "Chains after snow on the last climb.",
    why: "La Molina's twin with tree-lined runs and night skiing. Same Alp 2500 pass.",
    learnNote: "Beginner zone at the base; longer gentle runs through the trees than La Molina.",
    warn: "Night skiing is fun, not for first-timers.",
    tags: ["pyrenees"],
  },
  {
    id: "vallter", name: "Vallter 2000", area: "Setcases · Girona", region: "Catalunya",
    lat: 42.4246, lon: 2.2561, elev: 2000, top: { lat: 42.4300, lon: 2.2650, elev: 2535 },
    km: 18, lifts: 11, learn: 3, driveMin: 720, distKm: 1230,
    season: { open: "12-05", close: "04-06" },
    price: { low: 38, high: 42, rentSki: 25, rentBoard: 28, lessonGroup: 45, lessonPrivate: 60, parking: 0 },
    official: "https://vallter.cat",
    park: { lat: 42.4246, lon: 2.2561, text: "Free car park at the base at 2,000 m; the road up from Setcases is narrow." },
    route: "Via Barcelona, Ripoll and Camprodon.",
    chains: "Chains after snow on the access road.",
    why: "The easternmost resort in the Pyrenees, small and high, with the sea visible on a clear day.",
    learnNote: "Beginner zone by the base.",
    warn: "Wind-exposed; small.",
    tags: ["pyrenees", "small"],
  },
  {
    id: "vall-de-nuria", name: "Vall de Núria", area: "Queralbs · Girona", region: "Catalunya",
    lat: 42.3944, lon: 2.1550, elev: 1960, top: { lat: 42.4050, lon: 2.1500, elev: 2252 },
    km: 8, lifts: 5, learn: 5, driveMin: 720, distKm: 1220,
    season: { open: "12-05", close: "03-28" },
    price: { low: 30, high: 35, rentSki: 22, rentBoard: 25, lessonGroup: 40, lessonPrivate: 55, parking: 0 },
    official: "https://www.valldenuria.cat",
    park: { lat: 42.3730, lon: 2.1600, text: "No road at all — you park at Ribes de Freser or Queralbs and ride the rack railway up (about €25 return, included in some passes)." },
    route: "Via Barcelona and Ribes de Freser; the cog train does the rest.",
    chains: "None: no cars on the mountain.",
    why: "A valley with no road, a rack railway, a sanctuary and eight kilometres of gentle piste. The softest place to learn in Spain.",
    learnNote: "Every run is a beginner run. Carpets, a slow chair, and a school used to absolute first-timers.",
    warn: "Tiny: one day is plenty. Twelve hours from Rota.",
    tags: ["pyrenees", "beginner", "small", "train", "cheap"],
  },
];

/* Weekends and Spanish holidays make a day expensive and crowded. High-season
   windows below are the pattern Sierra Nevada and the Pyrenees use; exact
   dates change by resort and year. Dates are ISO strings. */
window.__SNOW_HOLIDAYS__ = [
  { from: "2026-12-05", to: "2026-12-08", name: "Puente de la Constitución" },
  { from: "2026-12-19", to: "2027-01-06", name: "Christmas and Reyes" },
  { from: "2027-02-27", to: "2027-03-01", name: "Día de Andalucía weekend" },
  { from: "2027-03-19", to: "2027-03-28", name: "Semana Santa" },
];

/* Typical snow on the ground at Sierra Nevada by month, base / top, in cm —
   used when a chosen date is beyond the sixteen-day forecast. Long-term
   pattern, not a promise. */
window.__SNOW_CLIMO__ = {
  "sierra-nevada": { 11: [15, 40], 12: [40, 90], 1: [70, 150], 2: [100, 200], 3: [110, 220], 4: [70, 180], 5: [20, 100] },
  pyrenees:        { 11: [20, 50], 12: [50, 100], 1: [80, 160], 2: [110, 200], 3: [120, 210], 4: [70, 160], 5: [0, 60] },
  central:         { 11: [0, 20], 12: [20, 50], 1: [40, 90], 2: [60, 110], 3: [50, 100], 4: [10, 40], 5: [0, 0] },
  north:           { 11: [0, 20], 12: [30, 60], 1: [60, 120], 2: [80, 150], 3: [70, 130], 4: [20, 60], 5: [0, 0] },
};

/* ---------- Learn ---------- */
window.__SNOW_LEARN__ = {
  verdict: {
    title: "Ski first. Here is why.",
    lines: [
      "Roller skating was hard because both feet roll in every direction and there is no brake. Skis are different: they only slide forwards, the boot locks your ankle so it cannot roll, and the very first thing you learn — the wedge, the \"pizza\" — is a brake. Most people are sliding down the beginner carpet slope and stopping on purpose before lunch on day one.",
      "Snowboarding is the opposite deal. Both feet are bolted to one board, sideways, so you cannot step, walk or catch yourself. Day one is mostly falling on your backside and your wrists, and it stays that way for two or three days. Then it clicks, and from there it gets easy faster than skiing does. The old line is true: skiing is easy to learn and hard to master; snowboarding is hard to learn and easy to master.",
      "For a first trip, four hours from home, with one day to spend: skis, a three-hour group lesson booked for the morning, everything rented. If you want to ride a board later, the mountain sense you learn on skis — reading slopes, lifts, snow, falling safely — carries straight over.",
    ],
  },
  falls: {
    title: "What falling is like",
    lines: [
      "Snow is not a rink floor. A beginner fall on skis at walking pace is a sit-down in something soft. Your bindings are set to release if you twist hard, so the ski comes off instead of your knee going with it.",
      "On skis the classic falls are sitting back onto the tails (harmless, embarrassing) and the slow-motion sideways topple when your skis cross. Both happen at 5 km/h.",
      "On a board the fall is a sudden catch of the uphill edge that slams you forward onto your hands or backwards onto your tailbone. Wrist guards and padded shorts are not optional on a board.",
      "Getting up on skis: put both skis across the slope, below you, and push up on the uphill hand. Getting up on a board: roll onto your knees facing uphill and stand from there.",
    ],
  },
  dayOne: {
    title: "Your first day, hour by hour",
    steps: [
      { t: "05:00", h: "Leave the base", p: "Four and a bit hours to Pradollano with one fuel stop in Granada. Tank full, chains in the boot, sandwiches made." },
      { t: "09:15", h: "Rental shop", p: "Boots first — they should be snug everywhere and hurt nowhere; say so if they pinch, they will change them. Then skis, poles, a helmet. Twenty minutes if you are early, an hour if you are not." },
      { t: "09:45", h: "Lift pass and gondola", p: "Buy the pass online the night before and collect at the machine. Ride the gondola from Pradollano up to Borreguiles, where the beginner slopes are." },
      { t: "10:00", h: "Group lesson, three hours", p: "How to put the skis on, how to walk, how to slide, the wedge stop, the wedge turn, the magic carpet, and by the end the slow chairlift. Do not skip this to save €55 — it is the whole trip." },
      { t: "13:00", h: "Lunch, sitting down", p: "Your legs will be shaking. Eat properly, drink a litre of water, take the boots' top buckles loose." },
      { t: "14:00", h: "Practise what you were shown", p: "Only on the beginner slope. Ninety minutes, then stop. Most beginners get hurt on the tired last run at four o'clock." },
      { t: "16:00", h: "Return the gear, drive down", p: "The A-395 down is 30 km of bends — go before dark. Sleep in Granada or drive home." },
    ],
  },
  basics: [
    { h: "Stopping: the wedge", p: "Tips of the skis together, tails apart, push the heels out. The bigger the wedge, the harder the brake. Weight on the inside edges of both skis. Look where you want to go, never at your feet." },
    { h: "Turning: shift the weight", p: "In the wedge, press harder on the right ski and you turn left; press on the left, you turn right. That is a whole day's skiing right there." },
    { h: "The magic carpet", p: "A conveyor belt. Ski onto it, stand still, ski off the end. It is how you get up the beginner slope without a lift." },
    { h: "The chairlift", p: "Look over your shoulder as it comes, sit, pull the bar down. At the top, tips up, bar up, stand and slide off in a straight line. Tell the lift attendant it is your first time and they slow it down." },
    { h: "Who has right of way", p: "The person below you. You are responsible for not hitting anyone downhill of you. Look uphill before you set off, and never stop in the middle of a run or under a lift." },
    { h: "Snowboard: one edge at a time", p: "Ride on the heel edge or the toe edge, never flat, never both. A flat board catches the downhill edge and throws you. Weight on the front foot, look where you are going." },
  ],
  fix: [
    { q: "I keep falling backwards", a: "You are sitting back. Press your shins into the front of the boots and keep your hands in front where you can see them. Every beginner does this." },
    { q: "I cannot stop", a: "Bigger wedge, heels further out, and weight on the inside edges of both skis. If the slope is too steep for your wedge to hold, you are on the wrong slope — go back to the beginner one." },
    { q: "My skis keep crossing", a: "Your weight is on the tails. Lean forward, keep the tips a hand's width apart, and turn one ski at a time, not both." },
    { q: "My feet hurt", a: "Boots too tight in one spot or too big and you are clenching. Loosen the top buckle first; if it is a pressure point, the rental shop will swap them. Thin socks, one pair." },
    { q: "I am exhausted after an hour", a: "Normal. Rest, eat, drink, and stop for the day at the point where you stop learning — that is when people get hurt." },
    { q: "The chairlift scares me", a: "Ask the attendant to slow it, pull the bar down, and watch the person in front of you get off. Nobody has ever been kept on a chairlift." },
    { q: "Board: I keep catching an edge", a: "You went flat. Commit to one edge — heel or toe — through the whole turn, and keep your weight on the front foot." },
    { q: "Board: my wrists and tailbone are killing me", a: "That is day one on a board. Wrist guards, impact shorts, and fall onto your forearms, not your palms." },
  ],
  after: {
    title: "The day after",
    lines: [
      "Quads, calves and shins will ache for two days. Walk, stretch, eat. It is the same muscles as a long hike downhill.",
      "Bruised tailbone and wrists on a board are normal; a wrist you cannot put weight on, a knee that swells, or a headache after hitting your head are a doctor's job, not this page's.",
      "Trip two: the wedge turns become parallel turns, you get onto a blue run, and it starts to feel like a sport. Three days on snow and you are a skier.",
    ],
  },
};

/* ---------- Gear ---------- */
window.__SNOW_GEAR__ = {
  rent: [
    { h: "Skis, boots, poles", p: "Rent. A beginner pack is €25–35 a day at the base of any resort; the ski school sells lesson-plus-rental bundles cheaper. Buying skis before you can turn is money on a bonfire." },
    { h: "Snowboard and boots", p: "Rent. €28–38 a day." },
    { h: "Helmet", p: "Rent the first time (€5–8 with the pack). Buy one if you go back: €40–70 at Decathlon." },
  ],
  buy: [
    { h: "Waterproof jacket and trousers", p: "The one thing that makes or breaks the day. Decathlon's own brand does a jacket for €50–80 and trousers for €40–60. Ski trousers, not hiking trousers: you will sit in snow a lot.", cost: "€90–140" },
    { h: "Gloves", p: "Waterproof, insulated ski gloves. Not knitted, not work gloves — wet hands end the day.", cost: "€20–40" },
    { h: "Goggles", p: "Sunglasses fall off when you fall and let snow in. Goggles with a medium (category 2–3) lens for Sierra Nevada's sun.", cost: "€25–50" },
    { h: "Ski socks", p: "One pair, tall, thin, made for skiing. Not cotton, and never two pairs — that is how you get cold feet.", cost: "€10–15" },
    { h: "Base layers", p: "A long-sleeve thermal top and leggings. Anything synthetic or merino you own already works. No cotton.", cost: "€20–40 or free" },
    { h: "Mid layer", p: "A fleece or a light puffer you already have.", cost: "free" },
    { h: "Neck gaiter", p: "A buff. Covers the gap under the helmet on the lift.", cost: "€5–10" },
    { h: "Sunscreen SPF 50 and lip balm", p: "Non-negotiable at 2,600 m in Andalusian sun. Reapply at lunch.", cost: "€10" },
    { h: "Board only: wrist guards and impact shorts", p: "The two things that make day one on a board survivable.", cost: "€30–60" },
    { h: "Snow chains", p: "Required in the car from December; the police check on the A-395. Buy the size for your tyres and fit them once in the driveway.", cost: "€40–70" },
  ],
  never: ["Jeans (soak through in an hour)", "Cotton hoodie or T-shirt as a base layer", "Sneakers or hiking boots for the drive-to-slope walk in slush — ski boots go on at the shop, so bring waterproof shoes", "Two pairs of socks", "Sunglasses instead of goggles"],
  where: [
    { h: "Decathlon", p: "El Puerto de Santa María and Jerez de la Frontera both have one, 15–25 minutes from the gate. Wedze is their snow brand; the whole list above costs about €250 there. Decathlon's Granada stores also rent skis if the resort shops are queued out.", url: "https://www.decathlon.es/es/tiendas" },
    { h: "MWR Outdoor Recreation, on base", p: "Outdoor Rec on most Navy installations rents ski and snowboard packages for a fraction of resort prices, and ITT sells Sierra Nevada day and weekend trips in season. Ask at the counter before you spend a euro — rules change and this page cannot check for you.", url: null },
    { h: "The resort base", p: "Pradollano has dozens of rental shops on Plaza de Andalucía and along the road up. Prices are all within a few euros; the ones the ski school uses have the shortest queue at nine." },
    { h: "Second-hand", p: "Wallapop is Spain's second-hand app and is full of once-used ski jackets and kids' helmets. Never buy used boots or a used helmet that has been in a crash.", url: "https://es.wallapop.com" },
  ],
  budget: [
    { k: "Fuel, Rota to Pradollano and back", v: "€80–100", n: "760 km round trip" },
    { k: "Tolls", v: "€0", n: "AP-4 is free now; the A-92 always was" },
    { k: "Parking at Pradollano", v: "€20–30 a day", n: "or €0 in Granada plus the bus" },
    { k: "Adult day pass", v: "€55–63", n: "Sierra Nevada, low to high season" },
    { k: "Ski or board rental", v: "€30", n: "with helmet" },
    { k: "Three-hour group lesson", v: "€50–60", n: "book the day before" },
    { k: "Lunch on the mountain", v: "€15–25", n: "or sandwiches from Granada" },
    { k: "One night in Granada", v: "€60–100", n: "Pradollano is €90–160" },
    { k: "Clothing you keep", v: "€250", n: "once, then it is free" },
  ],
};

/* ---------- Trip ---------- */
window.__SNOW_TRIP__ = {
  route: {
    title: "NAVSTA Rota to Pradollano",
    lines: [
      "380 km, about 4 h 15 without stops. Out of the gate onto the A-491 / A-4 towards Sevilla, round the SE-30 ring onto the A-92 signed Granada, then the Ronda Sur to the A-395 signed Sierra Nevada. The last 30 km climb from 700 m to 2,100 m through hairpins; allow 45 minutes for them in daylight and an hour in snow.",
      "Fuel and food in Granada, not on the mountain. There is one petrol station on the way up and the prices at the top are resort prices.",
      "Leave the base at five to be in the rental shop at a quarter past nine. Or drive up on Friday evening, sleep in Granada for €60, and start fresh — the better plan for a first day.",
    ],
  },
  chains: {
    title: "Chains, and when the road shuts",
    lines: [
      "From December to April the Guardia Civil can close the A-395 above the Collado de las Sabinas to cars without chains or winter tyres. It happens after every real snowfall, usually for a few hours in the morning.",
      "Buy chains for your tyre size (Decathlon, €40–70), fit them once at home, and keep gloves and a torch with them. Fitting chains for the first time at 06:30 in a blizzard on a hairpin is not the way to learn.",
      "Or park in Granada and take the ALSA bus: no chains, no parking, €5–9 each way, three departures a morning from the bus station.",
    ],
  },
  when: {
    title: "When to go, for a beginner",
    good: [
      "Weekdays in January, February and March: emptier slopes, cheaper passes, and the instructors have time for you.",
      "Late March and April: warm sun, soft snow that hurts less to fall on, spring prices, and lifts until 17:00.",
      "The first two weeks of December if the snow has arrived: quiet, and everything is new.",
    ],
    bad: [
      "6–8 December (the Constitution bridge), Christmas to 6 January, the Andalucía Day weekend at the end of February, and Semana Santa: the highest prices, the fullest car parks, the longest lift queues.",
      "Saturdays generally. If it has to be a weekend, Sunday is quieter than Saturday.",
      "The day after a big storm: the road is chains-only and the top is closed. Go the day after that.",
    ],
  },
  stay: {
    title: "Where to sleep",
    lines: [
      "Pradollano: the village at the lifts, 2,100 m. Walk to the gondola in your boots. €90–160 a night, and the bars are full of people who skied all day.",
      "Monachil and Güéjar Sierra: real villages 25–30 minutes below the resort, €50–90, olive trees and a river. Drive up in the morning.",
      "Granada: 45 minutes away, the cheapest beds, and the Alhambra lit up at night. The bus to the slopes leaves from the bus station.",
    ],
  },
  noCar: {
    title: "Without the car: fly and take the train",
    lines: [
      "Sevilla or Jerez to Barcelona is a €30–80 flight. From Barcelona Sants the R3 train runs straight to La Molina station in about three hours, and a shuttle bus climbs to the lifts. No chains, no car park, and La Molina is Spain's beginner resort.",
      "Vall de Núria has no road at all: train to Ribes de Freser, then the rack railway up.",
      "Sierra Nevada by public transport: train from Cádiz or Sevilla to Granada, then the ALSA bus up. Doable in a morning.",
    ],
  },
};

/* Words the site uses, in plain English. */
window.__SNOW_GLOSSARY__ = [
  { t: "Piste", d: "A marked, groomed run. Colour says difficulty: green easiest, blue easy, red hard, black expert. A first-timer stays on green and the beginner zone." },
  { t: "Beginner zone / debutantes", d: "The fenced, nearly flat area at the base with magic carpets. Where lessons happen." },
  { t: "Magic carpet", d: "A conveyor belt you stand on to go up the beginner slope." },
  { t: "Forfait", d: "Spanish for lift pass. A day pass is a forfait de día." },
  { t: "Wedge / pizza / snowplough", d: "Ski tips together, tails apart. The beginner's brake and first turn." },
  { t: "Base and top", d: "The lowest and highest lifts. Snow depth is reported at both; the top has more, the base is where you start." },
  { t: "Snow depth", d: "How much snow is on the ground. Under 30 cm at the base and the resort struggles to open lower runs; over 100 cm and everything is open." },
  { t: "Freezing level", d: "The height above which the air is below zero. If it is above the base, precipitation falls as rain there, not snow." },
  { t: "High season / temporada alta", d: "Weekends and holidays, when the pass costs more. Low season is weekdays outside the holidays." },
  { t: "Chains / cadenas", d: "Metal chains fitted over the driving tyres for snow. Legally required on the access road when the signs say so." },
];
